CXXFLAGS=-Wall

all : equityoptiontest 

equityoptiontest : ../src/blackscholesconstprocess.cpp equityoptiontest.cpp 
	g++ -g -o equityoptiontest ../src/blackscholesconstprocess.cpp equityoptiontest.cpp -l QuantLib
