CXXFLAGS=-Wall

all : blackscholesconstprocess 

blackscholesconstprocess : blackscholesconstprocess.hpp blackscholesconstprocess.cpp
	g++ -c blackscholesconstprocess.cpp -o blackscholesconstprocess.o -l QuantLib
